# Generated by Django 4.2 on 2023-05-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('air_temp', models.FloatField()),
                ('pressure', models.FloatField()),
                ('air_hum', models.FloatField()),
                ('soil_hum', models.FloatField()),
                ('soil_temp', models.FloatField()),
                ('light', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
