# Generated by Django 4.2 on 2023-05-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorvalue',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
