# Generated by Django 4.2 on 2023-05-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_sensorvalue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BustedPictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='busted_pictures/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
