# Generated by Django 4.2 on 2023-05-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_user_waterpumpelogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
