# Generated by Django 4.2.1 on 2023-05-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_rename_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
