# Generated by Django 4.2.1 on 2023-05-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='token',
            table='auth_token',
        ),
    ]
