# Generated by Django 4.2.1 on 2023-05-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_alter_token_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
